name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: cargo run --verbose
    - name: Send message
      run: curl -X POST https://gymskilltree.com/reload_all
